### ISSUE TITLE
Portabilidade para o editor Zed

### ISSUE THREAD

**Issue by leogm360** [larabeatrizms/astronaut-theme#1]
Olá, bom dia!

Existe algum problema se eu fizer uma portabilidade deste tema para o editor [Zed](https://zed.dev/) e atribuir créditos a você @larabeatrizms?

**Comment by larabeatrizms** [comment]
Boa noite @leogm360!
Pode fazer sim e ao invés de me dar créditos, pode dar ao Dracula theme! O astronaut-theme é totalmente baseado nele com algumas pequenas modificações
